# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - github-hook-notification

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  APP_NAME: node-app    # set this to your application's name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm prune --production
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: zip artifact    
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r name: ${{ env.APP_NAME }}.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: name: ${{ env.APP_NAME }}
          path: name: ${{ env.APP_NAME }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.APP_NAME }}

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.AZURE_WEBAPP_NAME }}.zip -d .

      - name: npm install, build, and test
        run: |
          rm -rf name: ${{ env.APP_NAME }}.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7F1BD448CA7547E7AD88262E37BF0098 }}
          package: .
